apiVersion: v1
kind: Service
metadata:
  name: conversion-webhook-service
  namespace: default
  labels:
    app: simple-kubernetes-webhook
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: simple-kubernetes-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-kubernetes-webhook
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-kubernetes-webhook
  replicas: 1 
  template:
    metadata:
      labels:
        app: simple-kubernetes-webhook
    spec:
      containers:
      - image: demo.goharbor.io/training/webhook:1.0.0
        name: simple-kubernetes-webhook
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 443

      imagePullSecrets:
        - name: registry

